# Generated by Django 5.1.2 on 2026-01-15 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacioncarga',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carga_academica', to='docentes.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncarga',
            unique_together={('docente', 'curso', 'materia')},
        ),
    ]
