# Generated by Django 5.1.2 on 2026-01-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionCarga',
        ),
    ]
