# Generated by Django 5.1.2 on 2026-01-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
    ]
