# Generated by Django 5.1.2 on 2026-01-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('docentes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, help_text='Ej: Primaria, Bachillerato', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='materia',
            name='area',
            field=models.CharField(blank=True, help_text='Ej: Ciencias, Humanidades, Artes', max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Ej: 10A, 11B, Preescolar', max_length=50, unique=True, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(default=1, verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Materia'),
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveIntegerField(default=2, verbose_name='Horas Semanales')),
                ('periodo_academico', models.CharField(default='2026', max_length=20, verbose_name='Período Académico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_materias', to='academico.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='docentes.docente', verbose_name='Docente Asignado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_cursos', to='academico.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Materia del Curso',
                'verbose_name_plural': 'Materias de los Cursos',
                'ordering': ['curso', 'materia'],
                'unique_together': {('curso', 'materia', 'periodo_academico')},
            },
        ),
    ]
