# Generated by Django 5.1.2 on 2026-03-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_curso_options_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursomateria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='anio_lectivo',
            field=models.PositiveIntegerField(default=2026, verbose_name='Año Lectivo'),
        ),
        migrations.AlterField(
            model_name='cursomateria',
            name='periodo_academico',
            field=models.CharField(default='1', max_length=20, verbose_name='Periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='cursomateria',
            unique_together={('curso', 'materia', 'periodo_academico', 'anio_lectivo')},
        ),
    ]
