# Generated by Django 6.0.1 on 2026-07-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_cursomateria_unique_together_and_more'),
        ('docentes', '0003_delete_asignacioncarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_tutor', to='docentes.docente', verbose_name='Tutor del Curso'),
        ),
        migrations.AddField(
            model_name='materia',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='materias', to='docentes.docente', verbose_name='Docentes'),
        ),
    ]
