# Generated by Django 5.1.2 on 2026-07-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_curso_tutor_materia_docentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Sede')),
                ('codigo_dane', models.CharField(blank=True, max_length=50, verbose_name='Código DANE')),
                ('zona', models.CharField(blank=True, help_text='Rural / Urbana', max_length=50, verbose_name='Zona')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='objetivo_p1',
            field=models.TextField(blank=True, verbose_name='Objetivo Periodo 1'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='objetivo_p2',
            field=models.TextField(blank=True, verbose_name='Objetivo Periodo 2'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='objetivo_p3',
            field=models.TextField(blank=True, verbose_name='Objetivo Periodo 3'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='objetivo_p4',
            field=models.TextField(blank=True, verbose_name='Objetivo Periodo 4'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Ej: 10A, 11B, Preescolar', max_length=50, verbose_name='Nombre del Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.sede', verbose_name='Sede'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'sede')},
        ),
    ]
