# Generated by Django 5.1.2 on 2026-07-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_sede_cursomateria_objetivo_p1_and_more'),
        ('docentes', '0003_delete_asignacioncarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_tutor', to='docentes.docente', verbose_name='Titular del Curso'),
        ),
    ]
