# Generated by Django 5.1.2 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_clase',
            field=models.PositiveSmallIntegerField(default=50, help_text='Ej: 45, 50 o 60 minutos', verbose_name='Duración de clase (minutos)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_descanso',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Duración del descanso (minutos)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_fin_jornada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin de jornada'),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_inicio_jornada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio de jornada'),
        ),
        migrations.AddField(
            model_name='curso',
            name='num_descansos',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Número de descansos'),
        ),
    ]
