# Generated by Django 5.1.2 on 2026-07-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_curso_duracion_clase_curso_duracion_descanso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descanso1_min',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Duración descanso 1 (min)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descanso2_min',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Duración descanso 2 (min)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descanso3_min',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Duración descanso 3 (min)'),
        ),
    ]
