# Generated by Django 5.1.2 on 2026-07-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_curso_descanso1_min_curso_descanso2_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='es_descanso',
            field=models.BooleanField(default=False, verbose_name='Es descanso'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.cursomateria', verbose_name='Materia del Curso'),
        ),
    ]
