# Generated by Django 5.1.2 on 2026-07-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_horario_es_descanso_alter_horario_curso_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.curso', verbose_name='Curso'),
        ),
    ]
