# Generated by Django 5.1.2 on 2026-07-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_horario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(max_length=50, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('1', 'Día 1'), ('2', 'Día 2'), ('3', 'Día 3'), ('4', 'Día 4'), ('5', 'Día 5')], max_length=10, verbose_name='Día'),
        ),
    ]
