# Generated by Django 5.1.2 on 2026-01-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aspirante', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('grado_interes', models.CharField(max_length=50)),
                ('nombre_acudiente', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
