# Generated by Django 5.1.2 on 2026-01-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='email_contacto',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='grado_interes',
            field=models.CharField(max_length=50, verbose_name='Grado de Interés'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='nombre_acudiente',
            field=models.CharField(max_length=200, verbose_name='Nombre del Acudiente'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='nombre_aspirante',
            field=models.CharField(max_length=200, verbose_name='Nombre del Aspirante'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='telefono_contacto',
            field=models.CharField(max_length=20, verbose_name='Teléfono de Contacto'),
        ),
    ]
