# Generated by Django 5.1.2 on 2026-01-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_alter_preinscripcion_email_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Preinscripción', 'verbose_name_plural': 'Preinscripciones'},
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Observaciones del administrador', verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='observaciones_solicitante',
            field=models.TextField(blank=True, verbose_name='Observaciones del Solicitante'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('aplazado', 'Aplazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud'),
        ),
    ]
