# Generated by Django 6.0.1 on 2026-01-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_alter_preinscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='acepta_politica',
            field=models.BooleanField(default=False, verbose_name='Autorización Tratamiento de Datos'),
        ),
    ]
