# Generated by Django 6.0.1 on 2026-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0004_preinscripcion_acepta_politica'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='certificado_sisben',
            field=models.FileField(blank=True, help_text='Certificado si aplica', null=True, upload_to='admisiones/documentos/', verbose_name='Certificado SISBEN'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='certificados_academicos',
            field=models.FileField(blank=True, help_text='Último boletín o certificado de notas', null=True, upload_to='admisiones/documentos/', verbose_name='Certificados Académicos'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='doc_identidad',
            field=models.FileField(blank=True, help_text='Copia del documento de identidad del aspirante', null=True, upload_to='admisiones/documentos/', verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='recibo_servicios',
            field=models.FileField(blank=True, help_text='Copia de un recibo reciente de servicios públicos', null=True, upload_to='admisiones/documentos/', verbose_name='Recibo de Servicios Públicos'),
        ),
    ]
