# Generated by Django 5.1.2 on 2026-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='academico.materia'),
        ),
    ]
