# Generated by Django 5.1.2 on 2026-01-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('estudiantes', '0003_estudiante_materias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='calificacion',
            name='periodo',
            field=models.CharField(default='1', help_text='Ej: 1, 2, 3, Final', max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(default=True, verbose_name='Asistió'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='estudiantes.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='acudiente',
            field=models.CharField(max_length=200, verbose_name='Acudiente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='academico.materia', verbose_name='Materias'),
        ),
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cedula', 'Cédula'), ('certificado_nacimiento', 'Certificado de Nacimiento'), ('certificado_notas', 'Certificado de Notas'), ('foto', 'Fotografía'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos_estudiantes/', verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Documento de Estudiante',
                'verbose_name_plural': 'Documentos de Estudiantes',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
