# Generated by Django 5.1.2 on 2026-01-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_curso_options_alter_materia_options_and_more'),
        ('estudiantes', '0004_alter_asistencia_options_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='curso_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.cursomateria', verbose_name='Materia del Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'curso_materia', 'periodo')},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='materias',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='materia',
        ),
    ]
