# Generated by Django 5.1.2 on 2026-01-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_curso_options_alter_materia_options_and_more'),
        ('estudiantes', '0005_alter_calificacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nota_evaluaciones',
            field=models.FloatField(default=0.0, verbose_name='Evaluaciones (30%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_examen',
            field=models.FloatField(default=0.0, verbose_name='Examen (40%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_tareas',
            field=models.FloatField(default=0.0, verbose_name='Tareas (30%)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='curso_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.cursomateria', verbose_name='Materia del Curso'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(default=0.0, verbose_name='Nota Periodo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='periodo',
            field=models.CharField(choices=[('1', 'Periodo 1'), ('2', 'Periodo 2'), ('3', 'Periodo 3'), ('4', 'Periodo 4')], default='1', max_length=10, verbose_name='Periodo'),
        ),
    ]
