# Generated by Django 5.1.2 on 2026-01-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_calificacion_nota_evaluaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='nota_evaluaciones',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota_examen',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota_tareas',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_hacer',
            field=models.FloatField(default=0.0, verbose_name='Hacer (45%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_saber_acumulada',
            field=models.FloatField(default=0.0, verbose_name='Saber Acumulado (25%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_saber_final',
            field=models.FloatField(default=0.0, verbose_name='Saber Final (20%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_ser_auto',
            field=models.FloatField(default=0.0, verbose_name='Autoevaluación (5%)'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nota_ser_comportamiento',
            field=models.FloatField(default=0.0, verbose_name='Comportamiento (5%)'),
        ),
    ]
