# Generated by Django 5.1.2 on 2026-01-18 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_curso_options_alter_materia_options_and_more'),
        ('estudiantes', '0007_remove_calificacion_nota_evaluaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota_hacer',
            field=models.FloatField(default=0.0, help_text='Promedio automático de tareas/trabajos', verbose_name='Hacer (45%)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota_saber_acumulada',
            field=models.FloatField(default=0.0, help_text='Promedio automático de evaluaciones', verbose_name='Saber Acumulado (25%)'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1', 'Periodo 1'), ('2', 'Periodo 2'), ('3', 'Periodo 3'), ('4', 'Periodo 4')], default='1', max_length=10, verbose_name='Periodo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('tipo', models.CharField(choices=[('SABER', 'Saber (Evaluación/Lección)'), ('HACER', 'Hacer (Tarea/Trabajo/Exposición)')], max_length=10, verbose_name='Tipo de Actividad')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('curso_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.cursomateria', verbose_name='Materia del Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0.0, verbose_name='Nota')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='estudiantes.actividad', verbose_name='Actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_actividades', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
