# Generated by Django 5.1.2 on 2026-03-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
    ]
