# Generated by Django 5.1.2 on 2026-07-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_remove_estudiante_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('TI', 'T.I'), ('CC', 'C.C'), ('CE', 'C.E'), ('PA', 'Pasaporte')], default='TI', max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
