# Generated by Django 5.1.2 on 2026-07-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_estudiante_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eps',
            field=models.CharField(blank=True, max_length=100, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estrato',
            field=models.CharField(blank=True, choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rh',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='RH'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
