# Generated by Django 5.1.2 on 2026-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_estudiante_barrio_estudiante_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='pago_certificado',
            field=models.BooleanField(default=False, help_text='Marcar cuando el estudiante haya pagado. Se desmarca automaticamente al generar el certificado.', verbose_name='Pago de Certificado'),
        ),
    ]
