# Generated by Django 5.1.2 on 2026-07-22 22:45

from django.db import migrations, models


def habilitar_todos_certificados(apps, schema_editor):
    Estudiante = apps.get_model('estudiantes', 'Estudiante')
    Estudiante.objects.filter(pago_certificado=False).update(pago_certificado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_pago_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='pago_certificado',
            field=models.BooleanField(default=True, help_text='Desmarcar para bloquear la descarga de certificados al estudiante. Por defecto todos pueden descargar.', verbose_name='Pago de Certificado'),
        ),
        migrations.RunPython(habilitar_todos_certificados, reverse_code=migrations.RunPython.noop),
    ]
