# Generated by Django 5.1.2 on 2026-07-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_alter_estudiante_pago_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='campesino',
            field=models.BooleanField(default=False, verbose_name='Campesino'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='categoria_aula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría de Aula'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado_matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado de Matrícula'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='etnia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fuente_recursos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fuente de Recursos'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='modelo_educativo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo Educativo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nui',
            field=models.CharField(blank=True, max_length=50, verbose_name='NUI'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, verbose_name='País de Origen'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='zona',
            field=models.CharField(blank=True, help_text='Rural / Urbana', max_length=50, verbose_name='Zona'),
        ),
    ]
