# Generated by Django 5.1.2 on 2026-07-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_curso_tutor'),
        ('estudiantes', '0015_estudiante_campesino_estudiante_categoria_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='curso_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.cursomateria', verbose_name='Materia'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'curso_materia', 'fecha')},
        ),
    ]
