# Generated by Django 5.1.2 on 2026-07-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0016_asistencia_curso_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1', 'Periodo 1'), ('2', 'Periodo 2'), ('3', 'Periodo 3'), ('4', 'Periodo 4')], max_length=2, verbose_name='Periodo')),
                ('anio_lectivo', models.PositiveIntegerField(default=2026, verbose_name='Año Lectivo')),
                ('nota', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Calificación Disciplinaria')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación Disciplinaria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['estudiante', 'periodo'],
                'unique_together': {('estudiante', 'periodo', 'anio_lectivo')},
            },
        ),
    ]
