# Generated by Django 5.1.2 on 2026-07-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0017_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('TI', 'T.I'), ('CC', 'C.C'), ('CE', 'C.E'), ('PA', 'Pasaporte'), ('RC', 'R.C')], default='TI', max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
