# Generated by Django 5.1.2 on 2026-01-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('valores', models.TextField()),
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
            },
        ),
    ]
