# Generated by Django 5.1.2 on 2026-01-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilarEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(help_text='Ejemplo: fas fa-book', max_length=50, verbose_name='Clase de Icono (FontAwesome)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Pilar Educativo',
                'verbose_name_plural': 'Pilares Educativos',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='foto_rector',
            field=models.ImageField(blank=True, null=True, upload_to='institucion/', verbose_name='Foto del Rector(a)'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='lema',
            field=models.CharField(blank=True, help_text='Frase corta que aparece en el banner principal', max_length=200, null=True, verbose_name='Lema o Tagline'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='mensaje_rectoria',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rectoría'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='nombre_rector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Rector(a)'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='historia',
            field=models.TextField(verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='mision',
            field=models.TextField(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='valores',
            field=models.TextField(verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='vision',
            field=models.TextField(verbose_name='Visión'),
        ),
    ]
