# Generated by Django 5.1.2 on 2026-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_pilareducativo_informacioninstitucional_foto_rector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioninstitucional',
            name='foto_historia',
            field=models.ImageField(blank=True, help_text='Imagen que acompaña la sección de historia', null=True, upload_to='institucion/', verbose_name='Imagen de Historia'),
        ),
    ]
