# Generated by Django 6.0.1 on 2026-01-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_informacioninstitucional_foto_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioninstitucional',
            name='aviso_privacidad_corto',
            field=models.TextField(blank=True, help_text='Texto que aparecerá en los formularios', null=True, verbose_name='Aviso de Privacidad Corto'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='politica_privacidad',
            field=models.TextField(blank=True, null=True, verbose_name='Política de Tratamiento de Datos Personales'),
        ),
    ]
