# Generated by Django 6.0.1 on 2026-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_informacioninstitucional_aviso_privacidad_corto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('archivo', models.FileField(upload_to='documentos_institucionales/', verbose_name='Archivo')),
                ('categoria', models.CharField(choices=[('manual', 'Manual de Convivencia'), ('decreto', 'Decretos y Resoluciones'), ('circular', 'Circulares'), ('general', 'Información General')], default='general', max_length=20, verbose_name='Categoría')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('publico', models.BooleanField(default=True, help_text='Si se desmarca, solo usuarios registrados podrán verlo', verbose_name='Es Público')),
            ],
            options={
                'verbose_name': 'Documento de Interés',
                'verbose_name_plural': 'Documentos de Interés',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
