# Generated by Django 5.1.2 on 2026-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_documentointeres'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True, verbose_name='Código de Verificación')),
                ('estudiante_nombre', models.CharField(max_length=300, verbose_name='Nombre del Estudiante')),
                ('estudiante_documento', models.CharField(max_length=60, verbose_name='Documento')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado')),
                ('nivel', models.CharField(blank=True, max_length=100, verbose_name='Nivel')),
                ('anio', models.PositiveIntegerField(verbose_name='Año Lectivo')),
                ('sede', models.CharField(blank=True, max_length=200, verbose_name='Sede')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('valido', models.BooleanField(default=True, verbose_name='Válido')),
            ],
            options={
                'verbose_name': 'Certificado Emitido',
                'verbose_name_plural': 'Certificados Emitidos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='calendario',
            field=models.CharField(blank=True, default='A', max_length=10, null=True, verbose_name='Calendario'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='codigo_documento',
            field=models.CharField(blank=True, default='CO-02', max_length=20, null=True, verbose_name='Código de Documento'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='dane',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código DANE'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='horario',
            field=models.CharField(blank=True, help_text='Ej: Lunes a viernes de 08:00 am a 02:20 pm', max_length=200, null=True, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='jornada',
            field=models.CharField(blank=True, default='Mañana', max_length=50, null=True, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='nombre_colegio',
            field=models.CharField(blank=True, help_text='Ej: Institución Educativa Agroambiental Agua Clara', max_length=200, null=True, verbose_name='Nombre de la Institución'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='rector_cc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.C. del Rector(a)'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='resolucion',
            field=models.CharField(blank=True, help_text='Ej: 01458-03-2012', max_length=100, null=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='sede_principal',
            field=models.CharField(blank=True, help_text='Ej: Centro Docente Agua Clara - Sede Principal', max_length=200, null=True, verbose_name='Sede Principal'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='version_documento',
            field=models.CharField(blank=True, default='01', max_length=10, null=True, verbose_name='Versión de Documento'),
        ),
    ]
